### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by psprint** [rocky/zshdb#20]
I've noticed that some of the tests are failing. I attach the relevant log.
[test-suite.log](https://github.com/rocky/zshdb/files/3640897/test-suite.log)

**Comment by rocky** [comment]
What's going on is that your "tty" command is reporting that the tty is not a tty presumably in Polish. 

Probably what should happen is that the Locale setting should be set to English before the tests are run. You are in a much better position to test this out. So perhaps you can make the change and try it.

**Comment by psprint** [comment]
I do confirm that running `LANG=C make test` does yield all the tests passing.
