### ISSUE TITLE
test-columns and test-msg fails

### ISSUE THREAD

**Issue by irl** [rocky/zshdb#3]
Hi,

I am attempting to update the zshdb package in Debian however I am noticing that the two tests test-columns and test-msg appear to fail.

The Debian bug can be found at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=796472#12 and I have attached a build log there.

This is being built in a Debian unstable (sid) environment and will have the versions of packages currently in sid. You can also see the versions in the build log.

Thanks,
Iain.

**Comment by rocky** [comment]
What is going on is that in your environment zsh's "builtin printf "%-3s" (or any negative %s) isn't. This isn't a zshdb bug but somehow a bug in your environment or with zsh as I understand it. (zsh has changed semantics? Doesn't seem likely here.)

Does  building outside of the debian "make" work in your environment?

**Comment by rocky** [comment]
Oh. And thanks for packaging zshdb for debian.

**Comment by irl** [comment]
Ah ok, so it works outside of the Debian builder chroot, but not inside. I'll investigate futher...

**Comment by irl** [comment]
Also works using the Debian tools to build outside the chroot, just building in the chroot seems to be broken. Would the lack of a tty be an issue?

**Comment by rocky** [comment]
> Would the lack of a tty be an issue?

I don't think so. More closely related is zsh itself and why it is not handling "%-Xs" correctly. A simple suggestion is to compare the zsh version with that outside. And inside perhaps you can run a little test of `builtin printf "%-10s" hi`which should look like this: 

```
hi
``` 
not 
```
        hi
```

**Comment by irl** [comment]
So I've got zsh 5.0.7 outside and 5.0.8 inside. Running inside the chroot interactively:

    orbiter% builtin printf "%-10s" hi  
            hi%

Which I guess is suboptimal. Any idea what would be causing this problem?

**Comment by rocky** [comment]
I have no idea. I recall that zsh has lots of modes, settings, options and behaviors that control things.

So my suggestion is to ask zsh folks on the zsh-help mailing lisg. I that zsh-users-subscribe@zsh.org ? 

zsh has lots of mode and opt

**Comment by irl** [comment]
Ok, I'm now discussing this with the Debian Zsh Packaging Team. As this is not a bug in zshdb but in zsh, I'll close the issue. I'll notify you by email once the package is in Debian (unless more problems arise).

**Comment by rocky** [comment]
Thanks. If the Debian Zsh Packaging Team doesn't work out, I have had good luck with the general users zsh mailing list.

**Comment by irl** [comment]
19:51:32              ft ╡ I bet this is caused by what is fixed in 35412
19:51:49               ∟ ╡ zsh-workers reference number that is.
19:52:17               ∟ ╡ http://www.zsh.org/mla/workers/2015/msg01336.html
19:52:28               ∟ ╡ So that's fixed upstream already.
19:52:54               ∟ ╡ There are talks about a 5.1 release in the immediate future.

So this is an upstream issue.
