### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by dbitouze** [rocky/zshdb#35]
There is a typo on [git-clone git://github.com/rocky/zshdb.git](https://github.com/rocky/zshdb/wiki/Installation#from-git): there shouldn't be any `-` between `git` and `clone` in `git-clone git://github.com/rocky/zshdb.git`

**Comment by rocky** [comment]
Thanks for noticing and reporting the problem. 

I am currently out of town on business for several days and cant get to this right now.

If you are up for it, if you put in a PR for this though,  I could approve it and it would get addressed faster.

**Comment by dbitouze** [comment]
>If you are up for it, if you put in a PR for this though, I could approve it and it would get addressed faster.

Done.
