### ISSUE TITLE
`load` command does not increment command counter

### ISSUE THREAD

**Issue by jansorg** [rocky/zshdb#37]
(I'm attempting to add support for zshdb to BashSupport Pro)

With zshdb 1.1.2, the "load" command does not increment the counter of the current command in `zshsb<...>`.
This is breaking a the integration with the BashSupport Pro plugin, which currently assumes that every command will increment the counter to know when to stop listening for command output.

```
# zshdb --version
zshdb, release 1.1.2

# zshdb --quiet --no-highlight /home/jansorg/test.sh 
(/home/jansorg/test.sh:1):
echo hello world
zshdb<0> load /home/jansorg/test1.zsh
File /home/jansorg/test1.zsh loaded.
zshdb<0> 
```
`load` does not seem to increment `zshdb<0>` to `zshdb<1>`. 
"step" does correctly increment it, though.

With bashdb, the output is `bashdb<1>` as I expected it:
```
# bashdb --quiet --no-highlight /home/jansorg/test.sh 
(/home/jansorg/test.sh:1):
1:      echo hello world
bashdb<0> load /home/jansorg/test1.zsh
File /home/jansorg/test1.zsh loaded.
bashdb<1> 
```

**Comment by rocky** [comment]
I will look at when I get a chance. It may take a day or so. I am guessing the problem is in `lib/processor.sh`.

**Comment by rocky** [comment]
Ok. That wasn't so bad. I think d778c4d fixes this.

**Comment by jansorg** [comment]
Thank you! Yes, I think this is fixed with the new commit.
