### ISSUE TITLE
Termination of debugged script terminates zshdb

### ISSUE THREAD

**Issue by jansorg** [rocky/zshdb#38]
Tested with HEAD of zshdb.

With this script `test.sh`:
```sh
echo hello world
exit 12
```

and these zshdb commands (`step` twice):
```sh
# zshdb --no-highlight --quiet ./test.sh 
(/home/jansorg/test.sh:1):
echo hello
zshdb<0> step
hello
(/home/jansorg/test.sh:2):
exit 12
zshdb<1> step
```

the session and zshdb is terminated, but IMHO it should print a message similar to bashdb (`Debugged program terminated with code 12. Use q to quit or R to restart.`)

**Comment by rocky** [comment]
Makes sense. I can add that when I get a chance.
